### ISSUE TITLE
INFO How run on windows

### ISSUE THREAD

**Issue by dawidmachon** [manghat/remove-html-from-csv#2]
You need to install these modules:

- pandas
- bs4
- lxml

example:
`python -m pip install bs4`

And in code change:
`a['clean_bs'] = a['question'].apply(remove_html_escape)`
to
`a['clean_bs'] = a[col].apply(remove_html_escape)`

**Comment by manghat** [comment]
I have yet to test this. But thank you. Did it work for you? 

Have updated the Readme and the code change.

**Comment by manghat** [comment]
Have updated the Readme and the code change.
